Do $$
BEGIN
-- Make id columns generated
ALTER TABLE cdm.procedure_occurrence ALTER COLUMN procedure_occurrence_id DROP IDENTITY IF EXISTS;
ALTER TABLE cdm.procedure_occurrence ALTER COLUMN procedure_occurrence_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE cdm.observation ALTER COLUMN observation_id DROP IDENTITY IF EXISTS;
ALTER TABLE cdm.observation ALTER COLUMN observation_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE cdm.condition_occurrence ALTER COLUMN condition_occurrence_id DROP IDENTITY IF EXISTS;
ALTER TABLE cdm.condition_occurrence ALTER COLUMN condition_occurrence_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE cdm.visit_occurrence ALTER COLUMN visit_occurrence_id DROP IDENTITY IF EXISTS;
ALTER TABLE cdm.visit_occurrence ALTER COLUMN visit_occurrence_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE cdm.observation_period ALTER COLUMN observation_period_id DROP IDENTITY IF EXISTS;
ALTER TABLE cdm.observation_period ALTER COLUMN observation_period_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE cdm.measurement ALTER COLUMN measurement_id DROP IDENTITY IF EXISTS;
ALTER TABLE cdm.measurement ALTER COLUMN measurement_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE cdm.person ALTER COLUMN person_id DROP IDENTITY IF EXISTS;
ALTER TABLE cdm.person ALTER COLUMN person_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE cdm.location ALTER COLUMN location_id DROP IDENTITY IF EXISTS;
ALTER TABLE cdm.location ALTER COLUMN location_id ADD GENERATED BY DEFAULT AS IDENTITY;

END
$$